### ISSUE TITLE
github actions zero out Dresden data

### ISSUE THREAD

**Issue by psteinb** [psteinb/covid19-curve-your-city#35]
@vv01f I see that the automated script that pulls the data for Dresden apparently zeros out all columns except `diagnosed`. Compare 6cd762d5e346c6a77367fe8dfc2ff879d875cc66 and 6419daa46f4c2eb8621c15a291f3652b6c35910b. The diff for the latter is intriguing! it changed all rows dating back to Mar 12. This might be due to changes on dresden.de. I am not sure. Could you please have a look?

**Comment by vv01f** [comment]
some nasty change indeed, that was supposed to be a feature to have the later corrections of earlier numbers included instead of just the last line added. now it seems they drop data (supposedly for "optimizing" storage or just out of bad practice) on `arcgis.com` – we do not pull anything from `dresden.de`.
Problem is I do not see how we can have it both ways as is, I'd say either we get just last line or take in the backward corrections. Anything else could be done manually as well. Will have a look tomorrow for doing both strategies of keeping data in separate files.

**Comment by psteinb** [comment]
Awesome! Thanks for clarification regarding `arcgis` vs `dresden.de`. let me know of you progress. I plan to revamp this project
this week and potentially work on the fit.

**Comment by vv01f** [comment]
pr ready, recently "lost" data back in place

**Comment by psteinb** [comment]
This is great news. Thanks for investing time in this.
